log_filter="info,reqwest=info,rustls=info,hyper_util=info,hyper=info,h2=info,matrix_sdk=info,eyeball=info"
proxy_id="24swh-4iaaa-aaaap-ahevq-cai"
history_id="qejor-xqaaa-aaaap-ahjaa-cai"
matrix_url="https://matrix.staging.catalyze.chat"
redis_url="redis://localhost:6379"
password=""
# redis_url="redis://redis:6379"
