log_filter="debug,reqwest=info,rustls=info,hyper_util=info,hyper=info"
proxy_id="bwm3m-wyaaa-aaaag-qdiua-cai"
history_id="2ut72-xaycq-4u3iu-ut232-pqz7y-httja-ufna4-vmvh3-tc2eb-cof6b-yqe"
interval="1"
limit="100"
matrix_url="https://matrix.org"

[redis]
url = "redis://localhost:6379"
queue = "events"
