version: "3.8"

services:
  relayer:
    image: ghcr.io/catalyze-software/relayer:b16628f2553f551f9ce2acdfb63fff28eaff45f0
    restart: always
    volumes:
      - ./config.toml:/config.yaml
    environment:
      - RELAYER_REDIS_URL=redis://redis:6379

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"] # save data to disk

volumes:
  redis-data:
